### ISSUE TITLE
Purpose of 'line'

### ISSUE THREAD

**Issue by y2k-shubham** [nektro/sdrie#2]
- What was the thought process behind addition of [`line *list.List` in `SdrieDataStore`](https://github.com/nektro/go.sdrie/blob/master/main.go#L11)?
 - I can't seem to figure out any valid use-case that it is serving

**Comment by y2k-shubham** [comment]
- I read in your post that `line` stores a list of *active keys*
 - but so does the our `data` (map) [until they get expired]
.
 - doesn't `line` sound redundant?

**Comment by nektro** [comment]
the map stores the K->V associations, while the list stores the K-time tuple in ascending order of expiration, so that the background goroutine checking keys only needs to check if the first item in the list is due to expire, as opposed to the entire list since it knows that all keys n+1 expire after key n.

**Comment by nektro** [comment]
this probably could've also been done with channels, but the above seemed like the most time/memory efficient solution at the time.

**Comment by y2k-shubham** [comment]
> the map stores the K->V associations, while the list stores the K-time tuple in ascending order of expiration, so that the background goroutine checking keys only needs to check if the first item in the list is due to expire, as opposed to the entire list since it knows that all keys n+1 expire after key n.

Ok I got the gist of it. However are you sure that the implementation really accounts for 

> ascending order of expiration

Because looking at the implementation of [`Set(..)`](https://github.com/nektro/go.sdrie/blob/master/main.go#L33) I dont see that we've factored-in "expiration-time". Instead we are simply [appending](https://github.com/nektro/go.sdrie/blob/master/main.go#L57) new keys at the end of `line` 
.
Which means that if I push key X with expiry of 10 seconds immediately followed by pushing of key Y with expiry of 2 seconds, then Y will be put at the end of `line` (after X) despite expiring before X

**Comment by y2k-shubham** [comment]
I believe here you've mistakenly implemented `line` as a queue whereas we really need a priority-queue (heap)

**Comment by nektro** [comment]
I see, it seems that was the original implementation idea, but I never got around to it.
