### ISSUE TITLE
Decreased lifespan because of MutexSet

### ISSUE THREAD

**Issue by y2k-shubham** [nektro/sdrie#3]
Problem
 - in set, we [determine expiration timestamp](https://github.com/nektro/go.sdrie/blob/master/main.go#L41) before `MutexSet`
 - while `MutexSet` could block for non-negligible time; thereby _eating away_ some of the lifespan of key, even before it was set
.
Proposed solution
 - we must calculation expiration timestamp [within `MutexSet`](https://github.com/nektro/go.sdrie/blob/master/main.go#L76) (instead of passing it)

**Comment by nektro** [comment]
very good point.
